# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addvalue.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addtext = QtWidgets.QLineEdit(self.centralwidget)
        self.addtext.setGeometry(QtCore.QRect(210, 80, 251, 51))
        self.addtext.setObjectName("addtext")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(250, 210, 171, 41))
        self.comboBox.setObjectName("comboBox")

        self.comboBox.currentIndexChanged.connect(self.com)

        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(270, 340, 161, 51))
        self.result.setText("")
        self.result.setObjectName("result")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(510, 90, 93, 28))
        self.add.setObjectName("add")

        self.add.clicked.connect(self.ad)

        self.remove = QtWidgets.QPushButton(self.centralwidget)
        self.remove.setGeometry(QtCore.QRect(520, 240, 93, 28))
        self.remove.setObjectName("remove")

        self.remove.clicked.connect(self.rem)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add.setText(_translate("MainWindow", "Add"))
        self.remove.setText(_translate("MainWindow", "Remove"))
    
    def ad(self):
        a=self.addtext.text()
        self.comboBox.addItem(a)
    def com(self):
        a=self.comboBox.currentText()
        self.result.setText(a)
    def rem(self):
        b=self.comboBox.currentIndex()
        self.comboBox.removeItem(b)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
