# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.c = QtWidgets.QCheckBox(self.centralwidget)
        self.c.setGeometry(QtCore.QRect(420, 170, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.c.setFont(font)
        self.c.setObjectName("c")
        self.head = QtWidgets.QLabel(self.centralwidget)
        self.head.setGeometry(QtCore.QRect(60, 120, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.head.setFont(font)
        self.head.setObjectName("head")
        self.j = QtWidgets.QCheckBox(self.centralwidget)
        self.j.setGeometry(QtCore.QRect(420, 210, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.j.setFont(font)
        self.j.setObjectName("j")
        self.p = QtWidgets.QCheckBox(self.centralwidget)
        self.p.setGeometry(QtCore.QRect(420, 250, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.p.setFont(font)
        self.p.setObjectName("p")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(260, 380, 211, 51))
        self.result.setText("")
        self.result.setObjectName("result")
        self.check = QtWidgets.QPushButton(self.centralwidget)
        self.check.setGeometry(QtCore.QRect(290, 300, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check.setFont(font)
        self.check.setObjectName("check")

        self.check.clicked.connect(self.che)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.c.setText(_translate("MainWindow", "C"))
        self.head.setText(_translate("MainWindow", "choose your programming language"))
        self.j.setText(_translate("MainWindow", "JAVA"))
        self.p.setText(_translate("MainWindow", "PYTHON"))
        self.check.setText(_translate("MainWindow", "Check"))
    
    def che(self):
        s=""
        if(self.c.isChecked()):
            s=s+"c"
        if(self.j.isChecked()):
            s=s+"j"
        if(self.p.isChecked()):
            s=s+"p"
        self.result.setText(s)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
