# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datalink.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nametext = QtWidgets.QLineEdit(self.centralwidget)
        self.nametext.setGeometry(QtCore.QRect(190, 110, 201, 41))
        self.nametext.setObjectName("nametext")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(440, 150, 93, 28))
        self.add.setObjectName("add")

        self.add.clicked.connect(self.db1)

        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(80, 110, 111, 41))
        self.name.setObjectName("name")
        self.class_2 = QtWidgets.QLabel(self.centralwidget)
        self.class_2.setGeometry(QtCore.QRect(80, 240, 111, 41))
        self.class_2.setObjectName("class_2")
        self.roll = QtWidgets.QLabel(self.centralwidget)
        self.roll.setGeometry(QtCore.QRect(80, 170, 111, 41))
        self.roll.setObjectName("roll")
        self.classtext = QtWidgets.QLineEdit(self.centralwidget)
        self.classtext.setGeometry(QtCore.QRect(190, 240, 201, 41))
        self.classtext.setObjectName("classtext")
        self.rolltext = QtWidgets.QLineEdit(self.centralwidget)
        self.rolltext.setGeometry(QtCore.QRect(190, 170, 201, 41))
        self.rolltext.setObjectName("rolltext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add.setText(_translate("MainWindow", "Add"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.class_2.setText(_translate("MainWindow", "Class"))
        self.roll.setText(_translate("MainWindow", "Roll"))

    def db1(self):
        n=self.nametext.text()
        r=self.rolltext.text()
        c=self.classtext.text()
        conn = sqlite3.connect("project.db")
        cur = conn.cursor()
        sql="insert into stu values(?,?,?)"
        val=(n,r,c)
        cur.execute(sql,val)
        conn.commit()
        if cur.rowcount==1:
            print("inserted")
        else:
            print("not")
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
