# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deldatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_Delete(object):
    def setupUi(self, Delete):
        Delete.setObjectName("Delete")
        Delete.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Delete)
        self.centralwidget.setObjectName("centralwidget")
        self.delbutton = QtWidgets.QPushButton(self.centralwidget)
        self.delbutton.setGeometry(QtCore.QRect(490, 210, 93, 28))
        self.delbutton.setObjectName("delbutton")

        self.delbutton.clicked.connect(self.de)
                                                  
        self.roll = QtWidgets.QLabel(self.centralwidget)
        self.roll.setGeometry(QtCore.QRect(90, 210, 81, 21))
        self.roll.setObjectName("roll")
        self.rolltext = QtWidgets.QLineEdit(self.centralwidget)
        self.rolltext.setGeometry(QtCore.QRect(210, 200, 231, 41))
        self.rolltext.setObjectName("rolltext")
        Delete.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Delete)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        Delete.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Delete)
        self.statusbar.setObjectName("statusbar")
        Delete.setStatusBar(self.statusbar)

        self.retranslateUi(Delete)
        QtCore.QMetaObject.connectSlotsByName(Delete)

    def retranslateUi(self, Delete):
        _translate = QtCore.QCoreApplication.translate
        Delete.setWindowTitle(_translate("Delete", "MainWindow"))
        self.delbutton.setText(_translate("Delete", "Delete"))
        self.roll.setText(_translate("Delete", "Enter Roll"))

    def de(self):
        r=self.rolltext.text()
        conn = sqlite3.connect("project.db")
        cur = conn.cursor()
        sql="delete from stu where roll=?"
        val=(r)
        cur.execute(sql,val)
        conn.commit()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Delete = QtWidgets.QMainWindow()
    ui = Ui_Delete()
    ui.setupUi(Delete)
    Delete.show()
    sys.exit(app.exec_())
