# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.c1 = QtWidgets.QPushButton(self.centralwidget)
        self.c1.setGeometry(QtCore.QRect(280, 230, 93, 28))
        self.c1.setObjectName("c1")
        self.c1.clicked.connect(self.dis)
        self.lb1 = QtWidgets.QLabel(self.centralwidget)
        self.lb1.setGeometry(QtCore.QRect(110, 140, 151, 41))
        self.lb1.setObjectName("lb1")
        self.l1 = QtWidgets.QLineEdit(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(220, 140, 231, 41))
        self.l1.setObjectName("l1")
        self.showtext = QtWidgets.QLabel(self.centralwidget)
        self.showtext.setGeometry(QtCore.QRect(240, 370, 131, 41))
        self.showtext.setText("")
        self.showtext.setObjectName("showtext")
        self.bt = QtWidgets.QLabel(self.centralwidget)
        self.bt.setGeometry(QtCore.QRect(110, 350, 181, 61))
        self.bt.setObjectName("bt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.c1.setText(_translate("MainWindow", "click"))
        self.lb1.setText(_translate("MainWindow", "Enter Name:"))
        self.bt.setText(_translate("MainWindow", "Enter name:"))
    def dis(self):
        name=self.l1.text()
        self.showtext.setText(name)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
