# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'empdata.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1228, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.insert = QtWidgets.QPushButton(self.centralwidget)
        self.insert.setGeometry(QtCore.QRect(750, 170, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(20)
        font.setItalic(True)
        self.insert.setFont(font)
        self.insert.setObjectName("insert")

        self.insert.clicked.connect(self.ins)

        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setGeometry(QtCore.QRect(820, 270, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(20)
        font.setItalic(True)
        self.update.setFont(font)
        self.update.setObjectName("update")

        self.update.clicked.connect(self.upd)

        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(890, 370, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(20)
        font.setItalic(True)
        self.delete_2.setFont(font)
        self.delete_2.setObjectName("delete_2")

        self.delete_2.clicked.connect(self.delt)

        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(110, 150, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.dept = QtWidgets.QLabel(self.centralwidget)
        self.dept.setGeometry(QtCore.QRect(110, 430, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dept.setFont(font)
        self.dept.setObjectName("dept")
        self.salary = QtWidgets.QLabel(self.centralwidget)
        self.salary.setGeometry(QtCore.QRect(110, 360, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.salary.setFont(font)
        self.salary.setObjectName("salary")
        self.id = QtWidgets.QLabel(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(110, 220, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.address = QtWidgets.QLabel(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(110, 290, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.address.setFont(font)
        self.address.setObjectName("address")
        self.nametext = QtWidgets.QLineEdit(self.centralwidget)
        self.nametext.setGeometry(QtCore.QRect(260, 150, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nametext.setFont(font)
        self.nametext.setObjectName("nametext")
        self.idtext = QtWidgets.QLineEdit(self.centralwidget)
        self.idtext.setGeometry(QtCore.QRect(260, 220, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.idtext.setFont(font)
        self.idtext.setObjectName("idtext")
        self.adrstext = QtWidgets.QLineEdit(self.centralwidget)
        self.adrstext.setGeometry(QtCore.QRect(260, 290, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.adrstext.setFont(font)
        self.adrstext.setObjectName("adrstext")
        self.saltext = QtWidgets.QLineEdit(self.centralwidget)
        self.saltext.setGeometry(QtCore.QRect(260, 360, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.saltext.setFont(font)
        self.saltext.setObjectName("saltext")
        self.depttext = QtWidgets.QLineEdit(self.centralwidget)
        self.depttext.setGeometry(QtCore.QRect(260, 430, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.depttext.setFont(font)
        self.depttext.setObjectName("depttext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1228, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.insert.setText(_translate("MainWindow", "Insert"))
        self.update.setText(_translate("MainWindow", "Update"))
        self.delete_2.setText(_translate("MainWindow", "Delete"))
        self.name.setText(_translate("MainWindow", "Emp Name:"))
        self.dept.setText(_translate("MainWindow", "Dept.:"))
        self.salary.setText(_translate("MainWindow", "Salary"))
        self.id.setText(_translate("MainWindow", "Emp ID:"))
        self.address.setText(_translate("MainWindow", "Address:"))

    def ins(self):
        # n=self.nametext.text()
        # i=self.idtext.text()
        # ad=self.adrstext.text()
        # s=self.saltext.text()
        # d=self.depttext.text()   
        # con=sqlite3.connect("project1.db")
        # cur=con.cursor()
        # sql="select count(EmpName) from emp where EmpName=?" 
        # cur.execute(sql,(n,))
        # result=cur.fetchall()
        # count=result[0][0]
        # if count>0:
        #     print("Already inserted")
        # else:

        #     sql="insert into emp values(?,?,?,?,?)" 
        #     val=(n,i,ad,s,d)
        #     cur.execute(sql,val)
        #     con.commit()
        pass

    def upd(self):
        # n=self.nametext.text()
        # i=self.idtext.text()
        # ad=self.adrstext.text()
        # s=self.saltext.text()
        # d=self.depttext.text()   
        # con=sqlite3.connect("project1.db")
        # cur=con.cursor()
        # sql="update emp set EmpName=?,Address=?,Salary=?,Dept=? where EmpID=?" 
        # val=(n,ad,s,d,i)
        # cur.execute(sql,val)
        # con.commit()
        pass

    def delt(self):
        # i=self.idtext.text()   
        # con=sqlite3.connect("project1.db")
        # cur=con.cursor()
        # sql="delete from emp where EmpID=?" 
        # val=(i,)
        # cur.execute(sql,val)
        # con.commit()
        pass



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
