# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(590, 150, 141, 41))
        self.add.setObjectName("add")

        self.add.clicked.connect(self.ad)

        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(260, 120, 201, 41))
        self.name.setObjectName("name")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(630, 290, 161, 51))
        self.result.setText("")
        self.result.setObjectName("result")
        self.dept = QtWidgets.QLineEdit(self.centralwidget)
        self.dept.setGeometry(QtCore.QRect(260, 170, 201, 41))
        self.dept.setObjectName("dept")
        self.remove = QtWidgets.QPushButton(self.centralwidget)
        self.remove.setGeometry(QtCore.QRect(590, 290, 141, 41))
        self.remove.setObjectName("remove")

        self.remove.clicked.connect(self.rem)

        self.show = QtWidgets.QPushButton(self.centralwidget)
        self.show.setGeometry(QtCore.QRect(590, 220, 141, 41))
        self.show.setObjectName("show")

        self.show.clicked.connect(self.sh)

        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(260, 460, 511, 231))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.RollNo = QtWidgets.QLineEdit(self.centralwidget)
        self.RollNo.setGeometry(QtCore.QRect(260, 220, 201, 41))
        self.RollNo.setObjectName("RollNo")
        self.Language_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Language_2.setGeometry(QtCore.QRect(260, 270, 201, 41))
        self.Language_2.setObjectName("Language_2")
        self.combo = QtWidgets.QComboBox(self.centralwidget)
        self.combo.setGeometry(QtCore.QRect(810, 220, 191, 51))
        self.combo.setObjectName("combo")

        #self.combo.currentIndexChanged.connect(self.com)

        self.combo.addItem("")
        self.fess = QtWidgets.QLineEdit(self.centralwidget)
        self.fess.setGeometry(QtCore.QRect(260, 330, 201, 41))
        self.fess.setObjectName("fess")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1210, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add.setText(_translate("MainWindow", "Add"))
        self.remove.setText(_translate("MainWindow", "Remove"))
        self.show.setText(_translate("MainWindow", "Show"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dept."))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Roll No"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Language"))
        self.combo.setItemText(0, _translate("MainWindow", "30000"))

    def ad(self):
        n=self.name.text()
        d=self.dept.text()
        r=self.RollNo.text()
        l=self.Language_2.text()
        rc=self.table.rowCount()
        self.table.insertRow(rc)
        self.table.setItem(rc,0,QtWidgets.QTableWidgetItem(n))
        self.table.setItem(rc,1,QtWidgets.QTableWidgetItem(d))
        self.table.setItem(rc,2,QtWidgets.QTableWidgetItem(r))
        self.table.setItem(rc,3,QtWidgets.QTableWidgetItem(l))
        a=self.fess.text()
        self.combo.addItem(a)

    def sh(self):
        i=self.table.currentIndex()
        rw=i.row()
        n=self.table.item(rw,0)
        print(n.text())
        n=self.table.item(rw,1)
        print(n.text())
        n=self.table.item(rw,2)
        print(n.text())
        n=self.table.item(rw,3)
        print(n.text())

    def rem(self):
        i=self.table.currentIndex()
        rw=i.ro+w()
        self.table.removeRow(rw)
        d=self.combo.currentIndex()
        self.combo.removeItem(d)
        # self.table.setRowCounr(0)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
