# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'malefemale.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_female(object):
    def setupUi(self, female):
        female.setObjectName("female")
        female.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(female)
        self.centralwidget.setObjectName("centralwidget")
        self.male = QtWidgets.QRadioButton(self.centralwidget)
        self.male.setGeometry(QtCore.QRect(210, 150, 95, 20))
        self.male.setObjectName("male")
        self.female_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.female_2.setGeometry(QtCore.QRect(390, 150, 95, 20))
        self.female_2.setObjectName("female_2")
        self.check = QtWidgets.QPushButton(self.centralwidget)
        self.check.setGeometry(QtCore.QRect(280, 210, 93, 28))
        self.check.setObjectName("check")
        self.ansshow = QtWidgets.QLabel(self.centralwidget)
        self.ansshow.setGeometry(QtCore.QRect(250, 280, 151, 31))
        self.ansshow.setText("")
        self.ansshow.setObjectName("ansshow")
        female.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(female)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        female.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(female)
        self.statusbar.setObjectName("statusbar")
        female.setStatusBar(self.statusbar)

        self.retranslateUi(female)
        QtCore.QMetaObject.connectSlotsByName(female)

    def retranslateUi(self, female):
        _translate = QtCore.QCoreApplication.translate
        female.setWindowTitle(_translate("female", "MainWindow"))
        self.male.setText(_translate("female", "Male"))
        self.female_2.setText(_translate("female", "Female"))
        self.check.setText(_translate("female", "check"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    female = QtWidgets.QMainWindow()
    ui = Ui_female()
    ui.setupUi(female)
    female.show()
    sys.exit(app.exec_())
