# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mul.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cal = QtWidgets.QPushButton(self.centralwidget)
        self.cal.setGeometry(QtCore.QRect(340, 220, 93, 28))
        self.cal.setObjectName("cal")
        self.cal.clicked.connect(self.mul)
        self.v1 = QtWidgets.QLineEdit(self.centralwidget)
        self.v1.setGeometry(QtCore.QRect(370, 60, 191, 41))
        self.v1.setObjectName("v1")
        self.v2 = QtWidgets.QLineEdit(self.centralwidget)
        self.v2.setGeometry(QtCore.QRect(370, 140, 191, 41))
        self.v2.setObjectName("v2")
        self.n1 = QtWidgets.QLabel(self.centralwidget)
        self.n1.setGeometry(QtCore.QRect(250, 70, 71, 31))
        self.n1.setObjectName("n1")
        self.n2 = QtWidgets.QLabel(self.centralwidget)
        self.n2.setGeometry(QtCore.QRect(250, 150, 71, 21))
        self.n2.setObjectName("n2")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(250, 290, 91, 21))
        self.result.setObjectName("result")
        self.blresult = QtWidgets.QLabel(self.centralwidget)
        self.blresult.setGeometry(QtCore.QRect(380, 290, 81, 21))
        self.blresult.setText("")
        self.blresult.setObjectName("blresult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cal.setText(_translate("MainWindow", "Calculate"))
        self.n1.setText(_translate("MainWindow", "Num1"))
        self.n2.setText(_translate("MainWindow", "Num2"))
        self.result.setText(_translate("MainWindow", "Result:"))
    def mul(self):
        n1=self.v1.text()
        n2=self.v2.text()
        m= int(n1) * int(n2)
        #print(m)
        self.blresult.setText(str(m))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
