    # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page2(object):
    
    def __init__(self,x):
        self.a=x
    
    def setupUi(self, page2):
        page2.setObjectName("page2")
        page2.resize(553, 855)
        self.centralwidget = QtWidgets.QWidget(page2)
        self.centralwidget.setObjectName("centralwidget")
        self.lable = QtWidgets.QLabel(self.centralwidget)
        self.lable.setGeometry(QtCore.QRect(200, 290, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lable.setFont(font)
        self.lable.setObjectName("lable")
        page2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(page2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 27))
        self.menubar.setObjectName("menubar")
        page2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(page2)
        self.statusbar.setObjectName("statusbar")
        page2.setStatusBar(self.statusbar)

        self.retranslateUi(page2)
        QtCore.QMetaObject.connectSlotsByName(page2)
        self.lable.setText(self.a)

    def retranslateUi(self, page2):
        _translate = QtCore.QCoreApplication.translate
        page2.setWindowTitle(_translate("page2", "MainWindow"))
        self.lable.setText(_translate("page2", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page2 = QtWidgets.QMainWindow()
    ui = Ui_page2()
    ui.setupUi(page2)
    page2.show()
    sys.exit(app.exec_())
