# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from page4 import *

class Ui_logpage(object):
    def setupUi(self, logpage):
        logpage.setObjectName("logpage")
        logpage.resize(596, 850)
        self.centralwidget = QtWidgets.QWidget(logpage)
        self.centralwidget.setObjectName("centralwidget")
        logpage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(logpage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 27))
        self.menubar.setObjectName("menubar")
        self.menuhome = QtWidgets.QMenu(self.menubar)
        self.menuhome.setObjectName("menuhome")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        logpage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(logpage)
        self.statusbar.setObjectName("statusbar")
        logpage.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(logpage)
        self.actionLogin.setObjectName("actionLogin")
        self.actionFailed = QtWidgets.QAction(logpage)
        self.actionFailed.setObjectName("actionFailed")
        self.actionSuccessfull = QtWidgets.QAction(logpage)
        self.actionSuccessfull.setObjectName("actionSuccessfull")
        self.actionVerify = QtWidgets.QAction(logpage)
        self.actionVerify.setObjectName("actionVerify")
        self.actionRecheck = QtWidgets.QAction(logpage)
        self.actionRecheck.setObjectName("actionRecheck")
        self.menuhome.addAction(self.actionLogin)
        self.menuhome.addAction(self.actionFailed)
        self.menuhome.addAction(self.actionSuccessfull)
        self.menuEdit.addAction(self.actionVerify)
        self.menuEdit.addAction(self.actionRecheck)
        self.menubar.addAction(self.menuhome.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.menubar.triggered[QtWidgets.QAction].connect(self.dis)

        self.retranslateUi(logpage)
        QtCore.QMetaObject.connectSlotsByName(logpage)

    def retranslateUi(self, logpage):
        _translate = QtCore.QCoreApplication.translate
        logpage.setWindowTitle(_translate("logpage", "MainWindow"))
        self.menuhome.setTitle(_translate("logpage", "home"))
        self.menuEdit.setTitle(_translate("logpage", "Edit"))
        self.actionLogin.setText(_translate("logpage", "Login"))
        self.actionFailed.setText(_translate("logpage", "Failed"))
        self.actionSuccessfull.setText(_translate("logpage", "Successfull"))
        self.actionVerify.setText(_translate("logpage", "Verify"))
        self.actionRecheck.setText(_translate("logpage", "Recheck"))
   
    def dis(self,action):
        txt = action.text()
        if txt == "Login":
            self.MainWindow = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.MainWindow)
            self.MainWindow.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    logpage = QtWidgets.QMainWindow()
    ui = Ui_logpage()
    ui.setupUi(logpage)
    logpage.show()
    sys.exit(app.exec_())
