# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from page2 import *

class Ui_page1(object):
    def setupUi(self, page1):
        page1.setObjectName("page1")
        page1.resize(628, 852)
        self.centralwidget = QtWidgets.QWidget(page1)
        self.centralwidget.setObjectName("centralwidget")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(200, 270, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button.setFont(font)
        self.button.setObjectName("button")

        self.button.clicked.connect(self.con)
        
        page1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(page1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 628, 27))
        self.menubar.setObjectName("menubar")
        page1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(page1)
        self.statusbar.setObjectName("statusbar")
        page1.setStatusBar(self.statusbar)

        self.retranslateUi(page1)
        QtCore.QMetaObject.connectSlotsByName(page1)

    def retranslateUi(self, page1):
        _translate = QtCore.QCoreApplication.translate
        page1.setWindowTitle(_translate("page1", "MainWindow"))
        self.button.setText(_translate("page1", "PushButton"))
    
    def con(self):
        self.a="welcome to 2nd page"
        self.page2 = QtWidgets.QMainWindow()
        self.ui = Ui_page2(self.a)
        self.ui.setupUi(self.page2)
        self.page2.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page1 = QtWidgets.QMainWindow()
    ui = Ui_page1()
    ui.setupUi(page1)
    page1.show()
    sys.exit(app.exec_())
