# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nametext = QtWidgets.QLineEdit(self.centralwidget)
        self.nametext.setGeometry(QtCore.QRect(100, 70, 171, 31))
        self.nametext.setObjectName("nametext")
        self.streamtext = QtWidgets.QLineEdit(self.centralwidget)
        self.streamtext.setGeometry(QtCore.QRect(100, 130, 171, 31))
        self.streamtext.setObjectName("streamtext")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 190, 171, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(80, 320, 371, 192))
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(460, 60, 93, 28))
        self.add.setObjectName("add")

        self.add.clicked.connect(self.ad)

        self.show = QtWidgets.QPushButton(self.centralwidget)
        self.show.setGeometry(QtCore.QRect(460, 120, 93, 28))
        self.show.setObjectName("show")

        self.show.clicked.connect(self.sh)

        self.remove1 = QtWidgets.QPushButton(self.centralwidget)
        self.remove1.setGeometry(QtCore.QRect(460, 180, 93, 28))
        self.remove1.setObjectName("remove1")

        self.remove1.clicked.connect(self.rem1)

        self.remove2 = QtWidgets.QPushButton(self.centralwidget)
        self.remove2.setGeometry(QtCore.QRect(460, 240, 93, 28))
        self.remove2.setObjectName("remove2")

        self.remove2.clicked.connect(self.rem2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Stream"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Regno"))
        self.add.setText(_translate("MainWindow", "Add"))
        self.show.setText(_translate("MainWindow", "Show"))
        self.remove1.setText(_translate("MainWindow", "Remove1"))
        self.remove2.setText(_translate("MainWindow", "Remove2"))
    
    def ad(self):
        n=self.nametext.text()
        s=self.streamtext.text()
        r=self.lineEdit_3.text()
        rc=self.table.rowCount()
        self.table.insertRow(rc)
        self.table.setItem(rc,0,QtWidgets.QTableWidgetItem(n))
        self.table.setItem(rc,1,QtWidgets.QTableWidgetItem(s))
        self.table.setItem(rc,2,QtWidgets.QTableWidgetItem(r))
    
    def sh(self):
        i=self.table.currentIndex()
        rw=i.row()
        n=self.table.item(rw,0)
        print(n.text())
        n=self.table.item(rw,1)
        print(n.text())
        n=self.table.item(rw,2)
        print(n.text())
    
    def rem1(self):
        i=self.table.currentIndex()
        rw=i.row()
        self.table.removeRow(rw)
    
    def rem2(self):
        self.table.setRowCount(0)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
