# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatedateabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(130, 140, 91, 31))
        self.name.setObjectName("name")
        self.class_2 = QtWidgets.QLabel(self.centralwidget)
        self.class_2.setGeometry(QtCore.QRect(130, 250, 91, 31))
        self.class_2.setObjectName("class_2")
        self.roll = QtWidgets.QLabel(self.centralwidget)
        self.roll.setGeometry(QtCore.QRect(130, 190, 91, 31))
        self.roll.setObjectName("roll")
        self.nametext = QtWidgets.QLineEdit(self.centralwidget)
        self.nametext.setGeometry(QtCore.QRect(220, 140, 191, 41))
        self.nametext.setObjectName("nametext")
        self.rolltext = QtWidgets.QLineEdit(self.centralwidget)
        self.rolltext.setGeometry(QtCore.QRect(220, 190, 191, 41))
        self.rolltext.setObjectName("rolltext")
        self.classtext = QtWidgets.QLineEdit(self.centralwidget)
        self.classtext.setGeometry(QtCore.QRect(220, 240, 191, 41))
        self.classtext.setObjectName("classtext")
        self.updatebutton = QtWidgets.QPushButton(self.centralwidget)
        self.updatebutton.setGeometry(QtCore.QRect(580, 200, 151, 41))
        self.updatebutton.setObjectName("updatebutton")

        self.updatebutton.clicked.connect(self.upd)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "Enter Name"))
        self.class_2.setText(_translate("MainWindow", "Enter class"))
        self.roll.setText(_translate("MainWindow", "Enter roll"))
        self.updatebutton.setText(_translate("MainWindow", "Update"))
    def upd(self):
        n=self.nametext.text()
        r=self.rolltext.text()
        c=self.classtext.text()
        conn = sqlite3.connect("project.db")
        cur = conn.cursor()
        sql="update stu set name=?,class=? where roll=?"
        val=(n,c,r)
        cur.execute(sql,val)
        conn.commit()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
