# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatedb.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox

class Ui_updatepage(object):
    def __init__(self,x,y,z):
        self.n=x
        self.r=y
        self.c=z

    def setupUi(self, updatepage):
        updatepage.setObjectName("updatepage")
        updatepage.resize(647, 828)
        self.centralwidget = QtWidgets.QWidget(updatepage)
        self.centralwidget.setObjectName("centralwidget")
        self.roll = QtWidgets.QLabel(self.centralwidget)
        self.roll.setGeometry(QtCore.QRect(70, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.roll.setFont(font)
        self.roll.setObjectName("roll")
        self.nametext = QtWidgets.QLineEdit(self.centralwidget)
        self.nametext.setGeometry(QtCore.QRect(180, 250, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nametext.setFont(font)
        self.nametext.setObjectName("nametext")
        self.class_2 = QtWidgets.QLabel(self.centralwidget)
        self.class_2.setGeometry(QtCore.QRect(70, 330, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.class_2.setFont(font)
        self.class_2.setObjectName("class_2")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(70, 260, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.classtext = QtWidgets.QLineEdit(self.centralwidget)
        self.classtext.setGeometry(QtCore.QRect(180, 330, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.classtext.setFont(font)
        self.classtext.setObjectName("classtext")
        self.updtext = QtWidgets.QPushButton(self.centralwidget)
        self.updtext.setGeometry(QtCore.QRect(260, 430, 201, 61))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.updtext.setFont(font)
        self.updtext.setObjectName("updtext")
        self.showroll = QtWidgets.QLabel(self.centralwidget)
        self.showroll.setGeometry(QtCore.QRect(180, 180, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.showroll.setFont(font)
        self.showroll.setText("")
        self.showroll.setObjectName("showroll")
        updatepage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(updatepage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 27))
        self.menubar.setObjectName("menubar")
        updatepage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(updatepage)
        self.statusbar.setObjectName("statusbar")
        updatepage.setStatusBar(self.statusbar)

        self.updtext.clicked.connect(self.upd)


        self.retranslateUi(updatepage)
        QtCore.QMetaObject.connectSlotsByName(updatepage)
        
        self.nametext.setText(self.n)
        self.showroll.setText(str(self.r))        
        self.classtext.setText(self.c)

    def retranslateUi(self, updatepage):
        _translate = QtCore.QCoreApplication.translate
        updatepage.setWindowTitle(_translate("updatepage", "MainWindow"))
        self.roll.setText(_translate("updatepage", "Roll:"))
        self.class_2.setText(_translate("updatepage", "Class:"))
        self.name.setText(_translate("updatepage", "Name:"))
        self.updtext.setText(_translate("updatepage", "Update"))

    def upd(self):
        n=self.nametext.text()
        r=self.showroll.text()
        c=self.classtext.text()
        con=sqlite3.connect("project2.db")
        cur=con.cursor()
        if  n=="" and c=="":
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Update")
                msg.setInformativeText("default") 
                msg.setWindowTitle("Pathfinder")
                msg.show()
                msg.exec_()
        else:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Update")
            msg.setInformativeText("updtae successful") 
            msg.setWindowTitle("Pathfinder")
            msg.show()
            msg.exec_()
            
            sql="update std_info set Name=?,Class=? where Roll=?" 
            val=(n,c,r)
            cur.execute(sql,val)
            con.commit()
        